let marksWeights = 78 ;
let marksHeight = 169 ;
let BMIMark=weightMark/(heightMark**2);
console.log(BMIMark);
let JohnsWeights =92 ;
let heightJohn=1.95;
let BMIJohn=weightJohn/(heightJohn**2);
console.log(BMIMark);
markHigherBMI=BMIMark>BMIJohn;
console.log(markHigherBMI);
